### ISSUE TITLE
Question on the SDK

### ISSUE THREAD

**Issue by Milerius** [immutable/imx-core-sdk-swift#60]
regarding: https://github.com/immutable/imx-core-sdk-swift/blob/ccf8273953ab31480081c3b50e381ad0d535d49d/Tests/ImmutableXCoreTests/Crypto/Stark/StarkKeyTests.swift#L32

on my side I believe the 2nd lowest bytes are `eaabcd39` for the address `0xa76e3eeb2f7143165618ab8feaabcd395b6fac7f`

as mentionned in: https://github.com/ethereum/EIPs/blob/master/EIPS/eip-2645.md eth_address_1 / eth_address_2 - the first and second 31 lowest bits of the corresponding eth_address.

Can you explain why if I convert to hex `1431804530` I don't find the second 31 lowest bits of the corresponding eth address? I think the correct value should be `3937127737`

**Comment by CassiusPacheco** [comment]
Hi @Milerius, the problem here is that `eaabcd39` is the 2nd last 32 bits of the address. 

To get the second last 31 bits we first need to convert the entire address into bits which gives us this value: `1010011101101110001111101110101100101111011100010100001100010110010101100001100010101011100011111110101010101011110011010011100101011011011011111010110001111111`

There we can find the second last 31 bits are `1010101010101111001101001110010` which is `1431804530` in decimals.

I hope this helps.

Thanks

**Comment by Milerius** [comment]
Thanks a lot! It work now
